In [ ]:
# imports
import time
import math
import json
import pickle
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline               

months = {"JAN": 0, "FEB": 1, "MAR": 2, "APR": 3, "MAY": 4, "JUN": 5, "JUL": 6, "AUG":7, "SEP":8, "OCT":9, "NOV": 10, "DEC":11}

## <i><u>PREPROCESSING</u></i>

In [ ]:
plt.rcParams['figure.figsize'] = (23, 10)
df = pd.read_csv('problem_1.csv')
df.head()

Business Unit Product Family             PLID Fiscal Quarter Fiscal Month  \
0         CSWBU           CBR8  CBR-D121-DS-MOD      Q1 FY2022   AUG FY2022   
1         CSWBU           CBR8  CBR-D121-DS-MOD      Q1 FY2022   OCT FY2022   
2         CSWBU           CBR8  CBR-D121-DS-MOD      Q1 FY2022   SEP FY2022   
3         CSWBU           CBR8  CBR-D121-DS-MOD      Q1 FY2002   AUG FY2002   
4         CSWBU           CBR8  CBR-D121-DS-MOD      Q1 FY2002   OCT FY2002   

   Booked_Qty Booking_Date  
0         204   01-08-2016  
1         564   01-10-2016  
2        1476   01-09-2016  
3         374   01-08-2017  
4        6094   01-10-2017

In [ ]:
array = df.to_numpy()
print(array)

[['CSWBU' 'CBR8' 'CBR-D121-DS-MOD' ... 'AUG FY2022' 204 '01-08-2016']
 ['CSWBU' 'CBR8' 'CBR-D121-DS-MOD' ... 'OCT FY2022' 564 '01-10-2016']
 ['CSWBU' 'CBR8' 'CBR-D121-DS-MOD' ... 'SEP FY2022' 1476 '01-09-2016']
 ...
 ['RTOBU' 'C980040' 'C9800-40-K9' ... 'JUL FY2012' 1231 '01-07-2021']
 ['RTOBU' 'C980040' 'C9800-40-K9' ... 'JUN FY2012' 591 '01-06-2021']
 ['RTOBU' 'C980040' 'C9800-40-K9' ... 'MAY FY2012' 601 '01-05-2021']]


In [ ]:
print(len(array))

10996


In [ ]:
# plot 1 [booked quantity VS business unit]

business_units = df["Business Unit"]
booked_quants = df["Booked_Qty"]


In [ ]:
# display plot
#plt.bar(business_units, booked_quants, color ='maroon', width = 0.4)
#plt.show()

In [ ]:
# plot 2 [booked quantity vs product family]

new_df = df[["Product Family", "Booked_Qty"]]
grouped = new_df.groupby("Product Family")['Booked_Qty'].sum()

array_2 = grouped.to_numpy()

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.precision', 3, ):
    grouped.head()

In [ ]:
df = pd.read_csv('problem_1.csv')

In [ ]:
parts = df["Booking_Date"].str.split("-", n = 3, expand = True)
df.head()
arr = df.to_numpy()

# separate date of order

# old method
# df["year"]= parts[2].astype('int')
# df["month"]= parts[1].astype('int')

# new method
df["month"] = df["Fiscal Month"].str[0:3].astype(str).map(months).astype(int)
df["year"] = df["Fiscal Month"].str[6:].astype(int)
df["year"].head()
df['prod_info'] = df['Business Unit'] + df['Product Family'] + df['PLID']

# print results
print(df['Business Unit'].nunique(),'Business Unit')
print(df['Product Family'].nunique(),'Product Family')
print(df['PLID'].nunique(),'PLID')
print(df['year'].nunique(),'year')
print(df['month'].nunique(),'month')

# replace features with numbers
df['Business Unit Val'], business_unit_u = pd.factorize(df['Business Unit'])
df['Product Family Val'], product_family_u = pd.factorize(df['Product Family'])
df['PLID Val'], plid_u = pd.factorize(df['PLID'])

# store numerifications into json
f = open("numerifications.json", 'w')
d = {"Business Unit": {}, "Product Family": {}, "PLID": {}}

for i, x in enumerate(business_unit_u):
    d["Business Unit"][i] = x

for i, x in enumerate(product_family_u):
    d["Product Family"][i] = x

for i, x in enumerate(plid_u):
    d["PLID"][i] = x

json.dump(d, f, indent = 4)
f.close()

# remove old features
df.drop('Fiscal Quarter', inplace=True, axis=1)
df.drop('Business Unit', inplace=True, axis=1)
df.drop('PLID', inplace=True, axis=1)
df.drop('Fiscal Month', inplace=True, axis=1)
df.drop('prod_info', inplace=True, axis=1)
df.drop('Product Family', inplace=True, axis=1)
df.drop('Booking_Date', inplace=True, axis=1)

data = df.copy()
df.head()

18 Business Unit
73 Product Family
250 PLID
9 year
12 month


Booked_Qty  month  year  Business Unit Val  Product Family Val  PLID Val
0         204      7  2022                  0                   0         0
1         564      9  2022                  0                   0         0
2        1476      8  2022                  0                   0         0
3         374      7  2002                  0                   0         0
4        6094      9  2002                  0                   0         0

In [ ]:
# x and y for training
ydf = df['Booked_Qty']
xdf = df[["Business Unit Val", "Product Family Val", "PLID Val", "month", "year"]]

# some stats
print(xdf["year"].unique())
print(xdf["month"].unique())

# convert to numpy
y = ydf.to_numpy()
x = xdf.to_numpy()

# save the numpy into pickle
fx = open("x_data.pickle", "wb")
fy = open("y_data.pickle", "wb")

pickle.dump(x, fx)
pickle.dump(y, fy)

fx.close()
fy.close()

print(x, y)

[2022 2002 2008 2007 2011 2012 2015 2014 2013]
[ 7  9  8 11  0 10  3  1  2  6  5  4]
[[   0    0    0    7 2022]
 [   0    0    0    9 2022]
 [   0    0    0    8 2022]
 ...
 [  17   72  249    6 2012]
 [  17   72  249    5 2012]
 [  17   72  249    4 2012]] [ 204  564 1476 ... 1231  591  601]


## <i><u>TRAINING</u></i>

In [ ]:
# imports
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# load data
fx = open("x_data.pickle", "rb")
fy = open("y_data.pickle", "rb")

x = pickle.load(fx)
y = pickle.load(fy)

fx.close()
fy.close()

In [ ]:
# split the data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
# linear regression 
LR = LinearRegression()
LR.fit(x_train, y_train)

LinearRegression()

## <i><u>TESTING</u></i>

In [ ]:
f = open("numerifications.json", 'r')
num = json.load(f)
num_order = ["Business Unit", "Product Family", "PLID"]
f.close()

In [ ]:
y_pred = LR.predict(x_test)
print(list(y_pred))

[2173.1278788057098, 12196.082984590175, 2372.493891333812, 11580.3065677126, 20215.39299727697, 6926.9561708008405, 956.9561128513596, 8372.913701015234, -2571.5627919299877, 16309.518256874551, 6203.94709120554, 16850.699890531658, 18943.149364388984, 6514.321762959764, 11445.85361720511, 19319.9110851961, 1203.6367814882833, 3388.61353229222, 16888.965083896648, 918.4970691066119, 9699.75932723665, 1102.1899394235224, 17063.88112468965, 19369.92308808706, 16322.881376217934, 19637.66326885004, 9618.18537102046, 3713.6575794120145, 2396.9567676248553, -1342.5212326684268, 2354.0651606027386, 6437.79209929661, 7816.222578688845, 3332.787389554607, 1227.0762722345826, 10689.387426792557, 3090.050035627093, 1497.144180956384, 16471.703126522538, 5219.292605383438, 6860.943953915383, 2341.6727752556617, 4227.003892517765, 15732.681305221951, 12361.460039777565, 18694.806448529358, 2717.088929899066, 19053.010330633988, 9635.528951354703, 19465.592900622694, 16546.632307815074, 17834.4862

In [ ]:
for i in range(20):
    print([num[num_order[j]][str(x_test[i][j])] for j in range(len(num_order))], f"{x_test[i][3]}/{x_test[i][4]}", y_pred[i])


['CSA', 'UCSCPU', 'UCS-CPU-I8276L'] 7/2022 2173.1278788057098
['TOASTBU', 'SEP25G', 'SFP-25G-SR-S'] 10/2007 12196.082984590175
['QKBU', 'N9300', 'N9K-C9364C'] 7/2007 2372.493891333812
['TOASTBU', 'QSFP100', 'QSFP-100G-DR-S'] 7/2022 11580.3065677126
['UCEBU', 'PHONVOC', 'CP-7841-K9'] 1/2022 20215.39299727697
['SRSBU', 'ISR1K', 'C1111-4P'] 7/2012 6926.9561708008405
['SRSBU', '4300ISR', 'ISR4331/K9'] 9/2012 956.9561128513596
['SRSBU', 'VIPTELA', 'VEDGE-2000-AC-K9'] 10/2007 8372.913701015234
['CRBU', 'NCS55FC', 'NCS-55A1-36H-SYS'] 11/2022 -2571.5627919299877
['UOPBLRBU', 'C9300', 'C9300-48T'] 9/2007 16309.518256874551
['EBBU', 'C9600', 'C9606R'] 6/2007 6203.94709120554
['UOPBLRBU', 'C9200L', 'C9200L-48P-4G-E'] 0/2022 16850.699890531658
['UOPBLRBU', 'C9400', 'C9400-SUP-1XL'] 9/2012 18943.149364388984
['CVEBU', 'CTSQS', 'CS-T10-TS+'] 6/2012 6514.321762959764
['TOASTBU', 'QSFP100', 'QSFP-100G-LR4-S'] 11/2022 11445.85361720511
['UCEBU', 'PHONVOC', 'CP-8841-K9'] 2/2011 19319.9110851961
['CSA', 

In [ ]:
# accuracy
mse = mean_squared_error(y_test, y_pred)
print(mse)

319796029.9696209


## <u><i>SIDE QUESTS</i><u><b>

In [ ]:
# load data
fx = open("x_data.pickle", "rb")
fy = open("y_data.pickle", "rb")

x = pickle.load(fx)
y = pickle.load(fy)

fx.close()
fy.close()

In [ ]:
x = np.array(x)
y = np.array(y)

for i in range()

SyntaxError: ignored